export const REMOVE_GARDEN_TEMPORAL = 'REMOVE_GARDEN_TEMPORAL';
export const UPDATE_GARDEN_TEMPORAL = 'UPDATE_GARDEN_TEMPORAL';
export const UPDATE_GARDEN_HAS_NOT_SAVED_CHANGES = 'UPDATE_GARDEN_HAS_NOT_SAVED_CHANGES';
