export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const REMOVE_USER_TEMPORAL = 'REMOVE_USER_TEMPORAL';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_CHANGES_TO_SAVE = 'UPDATE_USER_CHANGES_TO_SAVE';
export const UPDATE_USER_HAS_NOT_SAVED_CHANGES = 'UPDATE_USER_HAS_NOT_SAVED_CHANGES';
